### ISSUE TITLE
The task should also allow authorization using Azure AD

### ISSUE THREAD

**Issue by KRuusuv** [CommunityHiQ/Frends.Community.Azure.Blob#21]
The task should offer an authorization option that accepts a bearer token obtained from Azure AD.

https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobserviceclient.-ctor?view=azure-dotnet-preview#azure-storage-blobs-blobserviceclient-ctor(system-uri-azure-core-tokencredential-azure-storage-blobs-blobclientoptions)

https://learn.microsoft.com/en-us/azure/storage/common/storage-auth-aad-app?tabs=dotnet

**Comment by Svenskapojkarna** [comment]
Implemented in version 3.0.0.
