### ISSUE TITLE
DownloadBLobAsync does not work with special characters in blobName

### ISSUE THREAD

**Issue by juralaakkonen** [CommunityHiQ/Frends.Community.Azure.Blob#27]
DownloadBlobAsync: 
Cannot download blobs which has special characters in name.
Example: ListBlobs returns blob name: "testi_asi.aki[{rja:sd><fs.pdf", if you use that for Download, the blob is not found.
Tried to encode/escape blobname to formats:
- testi_asi.aki%5B%7Brja%3Asd%3E%3Cfs.pdf
- testi_asi.aki[%7Brja:sd%3E%3Cfs.pdf

But did not work - I believe it is because in GetBlobClient url is created with: `var url = new Uri($"https://{connection.StorageAccountName}.blob.core.windows.net/{containerName}/{blobName}");`.
This unescapes some characters, for example { and <

**Comment by juralaakkonen** [comment]
After further investigation it is not only the Uri creation that is causing this, as I was using connection string for download. Weird thing is that list blobs returns the name as is "testi_asi.aki[{rja:sd><fs.pdf", but when trying to download it with that name, it causes illegal characters in path exception. With escaped values the blob is not found...

**Comment by jefim** [comment]
The Uri creation should not be a problem - this seems to be a problem with local file system not allowing those special characters, so basically before setting the destination path on local file system the task should check for restricted symbols in file name and escape those.

**Comment by Svenskapojkarna** [comment]
This is a bit tricky to fix, since escaping characters does work in Linux, but for Windows escaping doesn't work, since Windows doesn't allow characters /, \, <, >, :, *, ?, " and | in filename. So I think those characters have to be removed to make it possible to use the task with both Windows and Linux. Thoughts?

**Comment by juralaakkonen** [comment]
Would it be possible to add "originalFileName" or similar property to the result, that would have the original name - this way the info is not lost. Removing characters that are not allowed in Windows environment is not an issue in my opinion.

**Comment by Svenskapojkarna** [comment]
Yeah this can be something we can do. We will add a new property to the result and we will add a toggle where user can select if he wants to replace illegal characters.

**Comment by Svenskapojkarna** [comment]
Hmm I wasn't able to replicate the issue.
I have the following Blob in a container:
![image](https://user-images.githubusercontent.com/36008914/210568965-60580e7d-049b-480c-850f-8e8c6915af1e.png)
I was able to download the blob using both Windows and Linux (although the file name in Windows didn't quite work, but the task was still able to download the blob successfully).
I have the following options:
![image](https://user-images.githubusercontent.com/36008914/210569367-ff7197db-14f2-4d34-831d-a9a11f3be6bc.png)
![image](https://user-images.githubusercontent.com/36008914/210569444-553d2188-ba36-49b6-b231-0adf065e897b.png)
@juralaakkonen Are you using similar options or is there some difference?

**Comment by Svenskapojkarna** [comment]
Tested with latest package version (3.1.0) and .NET Standard.

**Comment by juralaakkonen** [comment]
Customer version is 1.6.0 - when this issue occurred we first updated the package to latest at that time, but it broke the Task - we we had to revert back to 1.6.0. Is version 3.1.0 compatible with frends 5.4.3.312 now?

**Comment by Svenskapojkarna** [comment]
Managed to replicate this issue in Frends 5.4. It would seem that the error doesn't occur in Frends 5.5. I'm able to move forward with this now.

**Comment by Svenskapojkarna** [comment]
Implemented in version 3.2.0. You are now able to set option "parse illegal characters" on which will parse illegal characters from Blob name. Original Blob name added to result object. @juralaakkonen Could you test this out?

**Comment by juralaakkonen** [comment]
> Implemented in version 3.2.0. You are now able to set option "parse illegal characters" on which will parse illegal characters from Blob name. Original Blob name added to result object. @juralaakkonen Could you test this out?
@Svenskapojkarna 
Possibly introduced a new bug with this fix. You can no longer leave Encoding empty. With empty string you get error "Provided encoding is not supported. Please check supported encodings from Encoding-option.", with empty expression value you get Null reference Exception "Object reference not set to an instance of an object.". 
If Encoding is left empty, the Task should try to get the encoding set in Azure.
Because of this bug could not validate if the actual fix for filename works

**Comment by Svenskapojkarna** [comment]
New version (3.2.1) has been released where the above issue has been fixed.
@juralaakkonen Could you test again?

**Comment by juralaakkonen** [comment]
@Svenskapojkarna  tested with no Encoding and with a blob that had illegal characters in its name - fixes/changes to Task worked as intended - Thank you!
